format = """
$shell\
$username\
$directory\
$character
"""

# right prompt
right_format = """
$container
$git_branch
$git_state
$git_status
$git_metrics
"""

[username]
show_always = false

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_metrics]
disabled = false

# transient right prompt
[cmd_duration]
disabled = false
min_time = 50  # in ms
show_milliseconds = true
format = '[$duration]($style) '

[status]
disabled = false

[shell]
disabled = false
style = '#696969'
fish_indicator = '' # default shell
format = '[$indicator]($style)' # remove trailing space

bash_indicator = 'bsh '
zsh_indicator = 'zsh '
unknown_indicator = 'unknown shell '

format = """
$shell\
$username\
$directory\
$character
"""

# right prompt
right_format = """
$container
$git_branch
$git_state
$git_status
$git_metrics
"""

[username]
show_always = false

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_metrics]
disabled = false

# transient right prompt
[cmd_duration]
disabled = false
min_time = 50  # in ms
show_milliseconds = true
format = '[$duration]($style) '

[status]
disabled = false

[shell]
disabled = false
style = '#696969'
fish_indicator = '' # default shell
format = '[$indicator]($style)' # remove trailing space

bash_indicator = 'bsh '
zsh_indicator = 'zsh '
unknown_indicator = 'unknown shell '
