keys:
- hosts: &hosts
  - &guinea age1nm2yd7wed6gauzjyqca6e8ng45njcan0q2yfqaahjqsjurh2h5us6wjmw0
- users: &users
  - &sops_admin age1w4vzylklxkw07e0n86sz5yf7ug9akpq93z8uqwm83v4rvg7hhutqh05mgc
  - &pig age1ypf3q60pdwtj3j5c2zmd79z6ukwzlknm268gdkh3uj5mj89qyq7qw3pgmx
- all: &all
  - *sops_admin
  - *pig 
  - *guinea

creation_rules:
# IMPORTANT: ORDER MATTERS
# sops matches a file only; subsequent matches do not contribute to who can read a file
# Path relative to location of this file
- path_regex: secrets/common.yaml
  age: *all # potentially need to restrict users
- path_regex: secrets/host/guinea.+
  age: [*guinea, *sops_admin]
- path_regex: secrets/user/pig.+
  age: [*pig, *sops_admin ]
