keys:
- hosts:
  - &barrybenson age1vp49j2ldya959hu5xvxl2j0sdwtduazhzm7naylkxvvc9ywth93s7h9zux
  - &guinea age1hwdz0a8uc6un69ratp3eed9z4xd5c7279khpy66d7tcw8nlpfpgs8wkp2r
- users:
  - &allenl age16cn0jup2jdfejqxm0l60tkvtnd43t8aaqvs39qpy5q2nruvzu4jqvr8d7u
  - &pig age1ypf3q60pdwtj3j5c2zmd79z6ukwzlknm268gdkh3uj5mj89qyq7qw3pgmx
# ALWAYS add this key to secrets
- &sops_admin age1w4vzylklxkw07e0n86sz5yf7ug9akpq93z8uqwm83v4rvg7hhutqh05mgc

creation_rules:
# IMPORTANT: ORDER MATTERS
# once a file is matched by regex, subsequent matches do not contribute to who can read a file. specific rules first
# Paths should be relative to location of this file
#
# User secrets to be used by hosts
- path_regex: secrets/user/allenl/for_hosts.yaml
  age: [*allenl, *barrybenson, *sops_admin]
- path_regex: secrets/user/pig/for_hosts.yaml
  age: [*pig, *guinea, *sops_admin]

# host/user can read
- path_regex: secrets/host/barrybenson+
  age: [*barrybenson, *sops_admin]
- path_regex: secrets/host/guinea+
  age: [*guinea, *sops_admin]
- path_regex: secrets/user/allenl+
  age: [*allenl, *sops_admin]
- path_regex: secrets/user/pig+
  age: [*pig, *sops_admin]

# common
- path_regex: secrets/user/common.yaml
  age:
  - *allenl
  - *pig
  - *sops_admin
