# DAVs (radicale)
server {
    server_name dav.allenl.me;

    listen 8443 ssl;
    listen [::]:8443 ssl;

    include snippets/authelia-location.conf;

    # radicale
    location /radicale/ {
        limit_req zone=general burst=20 nodelay;
        limit_conn addr 10;

        include snippets/proxy.conf;
        include snippets/authelia-authrequest.conf;

        proxy_set_header  X-Script-Name /radicale;
        proxy_set_header  Host $http_host;
        proxy_pass_header Authorization;

        proxy_pass http://host.containers.internal:15080;
    }

    # radicale - add trailing slash 
    location = /radicale {
        return 301 $scheme://$host/radicale/;
    }
}
