# koito
server {
    server_name koito.allenl.me;

    listen 8443 ssl;
    listen [::]:8443 ssl;


    location / {
        include snippets/proxy.conf;
        proxy_pass http://host.containers.internal:20080;
    }
}
