# lldap
server {
    server_name lldap.allenl.me;

    listen 8443 ssl;
    listen [::]:8443 ssl;

    include snippets/authelia-location.conf;

    location / {
        include snippets/proxy.conf;
        include snippets/authelia-authrequest.conf;

        proxy_pass http://host.containers.internal:18080;
    }
}
