worker_processes auto;
# worker_rlimit_nofile 100000;

events {
    worker_connections 1024;
    use epoll; # linux optimization
    multi_accept on;
}

http {
    http2 on;

    # Main domain redirects to blog
    server {
        server_name allenl.me;

        listen 8443 ssl; 
        listen [::]:8443 ssl;

        location / {
            # limit_req zone=general nodelay;
            return 301 https://blog.allenl.me$request_uri;
        }
    } 

    # Import subdomains
    include sites/*.conf;

    # Redirects to main domain
    server {
        server_name www.allenl.me;

        listen 8443 ssl;
        listen [::]:8443 ssl;


        return 301 https://allenl.me$request_uri;
    }

    # Redirects all HTTP to HTTPS
    # Note: after all subdomain blocks
    server {
        server_name allenl.me *.allenl.me;

        listen 8080 default_server;
        listen [::]:8080 default_server;

        return 301 https://$host$request_uri;
    }

    # Catch-all for undefined domains (HTTPS)
    server {
        server_name _;  # matches anything not matched by other blocks

        listen 8443 ssl default_server reuseport;
        listen [::]:8443 ssl default_server reuseport;

        return 404;
    }

    include snippets/ssl.conf;
    include snippets/limit-rate-conn.conf;
    include snippets/compression.conf;
    include snippets/security-headers.conf;

    # Client timeouts
    client_body_timeout 12;
    client_header_timeout 12;
    keepalive_timeout 15;
    send_timeout 10;
    reset_timedout_connection on; # allow the server to close connection on non responding client, this will free up memory

    # Performance
    sendfile on;
    tcp_nopush on; # efficient file handling
    tcp_nodelay on; # low latency between requests

    # hide nginx version
    server_tokens off;

    # log for journalctl
    log_format detailed '[$time_local] $remote_addr $remote_user : '
                       '"$request" $status '
                       '"$http_referer" "$http_user_agent" '
                       '$request_time $upstream_response_time';
    access_log /dev/stdout detailed;
    error_log /dev/stderr warn;
    access_log /var/log/nginx/access_combined.log combined;

}
