# authelia 
server {
    server_name auth.allenl.me;

    listen 8443 ssl; 
    listen [::]:8443 ssl;

    location / {
        limit_req zone=general burst=30 nodelay;
        limit_conn addr 15;

        include snippets/proxy.conf;
        proxy_pass http://host.containers.internal:9080;
    }

    location = /api/verify {
      proxy_pass http://host.containers.internal:9080;
    }

    location /api/authz/ {
        proxy_pass http://host.containers.internal:9080;
    }
}
