# alsblog 
server {
    server_name blog.allenl.me;

    listen 8443 ssl; 
    listen [::]:8443 ssl;

    location / {
        #limit_req zone=general burst=50 nodelay;
        include snippets/proxy.conf;
        proxy_pass http://host.containers.internal:10080;
    }
}

