# pihole
server {
    server_name pihole.allenl.me;
        
    listen 8443 ssl;
    listen [::]:8443 ssl;

    include snippets/authelia-location.conf;

    location = / {
	    return 301 https://pihole.allenl.me/admin;
    }

    location / {
        include snippets/proxy.conf;
        include snippets/authelia-authrequest.conf;
        proxy_pass http://host.containers.internal:30080;
	}
}
