name: nix-flake-check

on:
  push:
    paths:
      - "**.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nix-community/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: Restore Nix cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-

      - name: Run checks
        working-directory: nix
        run: nix shell nixpkgs#just -c just flake-check
